export const textoIntroducaoMorse =
  'O código Morse pode ser usado em atividades escoteiras para treinar comunicação, atenção e transmissão de mensagens simples usando pontos e traços.';

export const codigoMorse = {
  A: '.-',
  B: '-...',
  C: '-.-.',
  D: '-..',
  E: '.',
  F: '..-.',
  G: '--.',
  H: '....',
  I: '..',
  J: '.---',
  K: '-.-',
  L: '.-..',
  M: '--',
  N: '-.',
  O: '---',
  P: '.--.',
  Q: '--.-',
  R: '.-.',
  S: '...',
  T: '-',
  U: '..-',
  V: '...-',
  W: '.--',
  X: '-..-',
  Y: '-.--',
  Z: '--..',
  0: '-----',
  1: '.----',
  2: '..---',
  3: '...--',
  4: '....-',
  5: '.....',
  6: '-....',
  7: '--...',
  8: '---..',
  9: '----.',
};

export const alfabetoMorse = Object.keys(codigoMorse).map((caractere) => ({
  caractere,
  codigo: codigoMorse[caractere],
}));
