export const textoIntroducaoNos =
  'Saber fazer o nó certo para o momento certo é uma habilidade fundamental. Aqui você encontra o passo a passo dos principais nós utilizados no movimento: desde o básico Direito para uniões simples, até o de Pescador para unir aquelas duas cordas.\n\nExplore, pratique e nunca esqueça: um nó escoteiro é aquele que resiste ao esforço, mas é fácil de desatar quando a tarefa termina.';

export const nosEscoteiros = [
  {
    id: 'direito',
    nome: 'Nó Direito',
    categoria: 'principal',
    imagemMenu: require('../../assets/no-direito-menu.png'),
    videoId: 'o5WD0y81dgw',
    videoUrl: 'https://youtu.be/o5WD0y81dgw?si=35YVcOa6rJ5VHnaL',
    regra: 'Direita sobre esquerda, depois esquerda sobre direita.',
    passos: [
      'Cruze a ponta da direita sobre a da esquerda. Torça.',
      'Cruze a nova ponta da esquerda sobre a da direita. Torça.',
      'Aperte tensionando as quatro partes da corda.',
    ],
    usos: [
      'Unir cordas de mesma espessura.',
      'Primeiros socorros: para bandagens e ataduras.',
      'Pacotes: para amarrar fardos ou embrulhos simples.',
    ],
    cuidado: 'Não use para segurança de vida ou cargas pesadas.',
  },
  {
    id: 'escota',
    nome: 'Nó de Escota',
    categoria: 'principal',
    imagemMenu: require('../../assets/no-escota-menu.png'),
    videoId: '72forZPbnDQ',
    videoUrl: 'https://youtu.be/72forZPbnDQ?si=UsVt8fAnTzIXYBUt',
    regra: 'A corda mais grossa faz a alça, a mais fina faz o trabalho.',
    passos: [
      'Faça uma dobra em forma de U com a corda mais grossa.',
      'Passe a corda fina por dentro dessa dobra, de baixo para cima.',
      'Contorne a parte de trás da dobra grossa com a corda fina.',
      'Passe a ponta da fina por baixo dela mesma e aperte.',
    ],
    usos: [
      'Unir cordas de espessuras ou materiais diferentes.',
      'Bandeiras: muito usado para prender o cabo à alça da bandeira.',
      'Quando o nó direito não segura bem.',
    ],
  },
  {
    id: 'pescador',
    nome: 'Nó do Pescador',
    categoria: 'principal',
    imagemMenu: require('../../assets/no-de-pescador-menu.png'),
    videoId: 'eKxjsmp1QAw',
    videoUrl: 'https://youtu.be/eKxjsmp1QAw?si=3mwZAJw2I79IgcJY',
    regra: 'Dois nós simples que se abraçam para travar a união.',
    passos: [
      'Alinhe as pontas das duas cordas lado a lado, apontando para sentidos opostos.',
      'Dê um nó simples com a ponta da primeira corda em volta da segunda corda.',
      'Dê um nó simples com a ponta da segunda corda em volta da primeira corda.',
      'Puxe as cordas principais até que os dois nós deslizem e travem um no outro.',
    ],
    usos: [
      'Unir fios de nylon, linhas de pesca ou cordas muito finas.',
      'Quando se precisa de uma união que não corra o risco de soltar.',
    ],
    cuidado: 'Esse nó é extremamente difícil de desatar após receber muita carga.',
  },
  {
    id: 'oito',
    nome: 'Nó em Oito',
    categoria: 'principal',
    imagemMenu: require('../../assets/no-em-oito-menu.png'),
    videoId: 'KmoZvouFyrU',
    videoUrl: 'https://youtu.be/KmoZvouFyrU?si=CIajcvDTYDUeY7L5',
    regra: 'Desenhe um oito para travar a ponta do cabo.',
    passos: [
      'Faça uma volta com a ponta da corda.',
      'Passe a ponta por trás da corda principal.',
      'Passe a ponta por dentro da volta, entrando pela frente.',
      'Puxe as extremidades para formar e firmar o desenho do número 8.',
    ],
    usos: [
      'Retenção: impede que a corda escape através de roldanas, furos ou ilhoses.',
      'Segurança: é um nó que não escorrega e é muito fácil de desatar, mesmo após sofrer forte tensão.',
    ],
    cuidado: 'Use apenas como nó de parada ou base; nunca utilize este método para unir duas cordas diferentes.',
  },
  {
    id: 'catau',
    nome: 'Nó Catau',
    categoria: 'geral',
    videoId: 'PXYXx9DRDgk',
    videoUrl: 'https://youtu.be/PXYXx9DRDgk?si=aOnAIu7jnjUNMFyX',
    regra: 'Encurta uma corda sem precisar cortá-la.',
    passos: [
      'Dobre a corda formando três partes paralelas.',
      'Faça uma meia-volta em uma extremidade e passe a dobra por dentro.',
      'Repita o processo na outra extremidade.',
      'Tensione as pontas principais para firmar o encurtamento.',
    ],
    usos: [
      'Reduzir temporariamente o comprimento de uma corda.',
      'Isolar uma parte desgastada da corda sem usá-la sob tensão.',
    ],
    cuidado: 'Só funciona bem quando a corda permanece tensionada.',
  },
  {
    id: 'volta-salteador',
    nome: 'Volta do Salteador',
    categoria: 'geral',
    videoId: 'QTq2bJkew0M',
    videoUrl: 'https://youtu.be/QTq2bJkew0M?si=jtrl1iFmHDBO1GEG',
    regra: 'Prende com segurança e permite soltar puxando a ponta livre.',
    passos: [
      'Passe a corda ao redor do apoio.',
      'Forme uma alça com a ponta de trabalho.',
      'Passe uma nova alça por dentro da primeira.',
      'Ajuste a tensão e deixe uma ponta livre para desmanchar o nó.',
    ],
    usos: [
      'Amarrações temporárias.',
      'Situações em que é preciso soltar a corda rapidamente.',
    ],
    cuidado: 'Não use em situações de risco pessoal ou carga crítica.',
  },
  {
    id: 'lais-guia',
    nome: 'Nó Lais de Guia',
    nomeLista: 'Nó Lais de Guia',
    categoria: 'geral',
    videoId: 'N7sgwuZoVlc',
    videoUrl: 'https://youtu.be/N7sgwuZoVlc?si=4Q3VEfsq_r4jUXCb',
    regra: 'Forma uma alça fixa que não corre.',
    passos: [
      'Faça uma pequena volta na corda principal.',
      'Passe a ponta livre por dentro da volta.',
      'Contorne a corda principal com a ponta livre.',
      'Volte a ponta pelo mesmo caminho da primeira volta e aperte.',
    ],
    usos: [
      'Criar uma alça firme na ponta da corda.',
      'Resgates, amarrações e trabalhos de campo que exigem uma alça que não aperte.',
    ],
  },
  {
    id: 'ordinario',
    nome: 'Nó Ordinário',
    categoria: 'geral',
    videoId: 'SHzwHLhZ3T4',
    videoUrl: 'https://youtu.be/SHzwHLhZ3T4?si=aT8d99XvZUtSnLXb',
    regra: 'Nó simples usado como base para muitos outros nós.',
    passos: [
      'Faça uma volta com a ponta da corda.',
      'Passe a ponta livre por dentro dessa volta.',
      'Puxe as duas partes da corda para apertar.',
    ],
    usos: [
      'Servir como nó de parada simples.',
      'Base para aprender outros nós.',
      'Amarrações rápidas de baixa exigência.',
    ],
    cuidado: 'Pode apertar muito e ficar difícil de desfazer após grande tensão.',
  },
];
